// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package register

import (
	"e-course-management/internal/register/delivery/http"
	register2 "e-course-management/internal/register/usecase"
	"e-course-management/internal/user/repository"
	user2 "e-course-management/internal/user/usecase"
	"e-course-management/pkg/mail/sendgrid"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *register.RegisterHandler {
	userRepository := user.NewUserRepository(db)
	userUseCase := user2.NewUserUseCase(userRepository)
	mailMail := mail.NewMailUseCase()
	registerUseCase := register2.NewRegisterUseCase(userUseCase, mailMail)
	registerHandler := register.NewRegisterHandler(registerUseCase)
	return registerHandler
}
