// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package forgot_password

import (
	"e-course-management/internal/forgot_password/delivery/http"
	forgot_password2 "e-course-management/internal/forgot_password/repository"
	forgot_password3 "e-course-management/internal/forgot_password/usecase"
	"e-course-management/internal/user/repository"
	user2 "e-course-management/internal/user/usecase"
	"e-course-management/pkg/mail/sendgrid"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *forgot_password.ForgotPasswordHandler {
	forgotPasswordRepository := forgot_password2.NewForgotPasswordRepository(db)
	userRepository := user.NewUserRepository(db)
	userUseCase := user2.NewUserUseCase(userRepository)
	mailMail := mail.NewMailUseCase()
	forgotPasswordUseCase := forgot_password3.NewForgotPasswordUseCase(forgotPasswordRepository, userUseCase, mailMail)
	forgotPasswordHandler := forgot_password.NewForgotPasswordHandler(forgotPasswordUseCase)
	return forgotPasswordHandler
}
